server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.66:3306/kele?useSSL=false&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1172477133wQ?