server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://47.106.38.136:3306/kele?useSSL=false&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1172477133wq