server:
  port: 8080

spring:
  datasource:
    url: # your jdbc url
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: # your db username
    password: # your db password?

  redis:
    host: # your redis host
    port: # your redis port
    password: # your redis password
    timeout: 10000
    lettuce:
      pool:
        max-active: 20
        min-idle: 5
        max-idle: 20
        max-wait: 5000ms

  mail:
    host: # your email host
    port: # your email port
    username: # your email account
    password: # your password
    properties:
      mail:
        debug: true
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          ssl:
            enable: true
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true

aes:
  decryptKey: #token encrypt key