server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kele?useSSL=false&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1172477133wq

  redis:
    host: 127.0.0.1
    port: 6379
    password: 1172477133wQ?
    timeout: 10000
    lettuce:
      pool:
        max-active: 20
        min-idle: 5
        max-idle: 20
        max-wait: 5000ms

  mail:
    host: smtp.zoho.com.cn
    port: 465
    protocol: smtp
    username: kele@virgoo.cc
    password: 1172477133wQ?
    properties:
      mail:
        smtp:
          ssl:
            enable: true